version: "3.7"
services:
  health-booklet-api:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules/
    container_name: health-booklet-api
    environment:
      - PORT=5000
      - NODE_ENV=production
    ports:
      - "5000:5000"
    command: bash -c "npm i ts-node typescript -g && npm install && npm run start"